tap "argoproj/tap"
tap "hashicorp/tap"
tap "hidetatz/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "hudochenkov/sshpass"
tap "weaveworks/tap"
brew "argocd"
brew "python@3.10"
brew "asciinema"
brew "python@3.11"
brew "docutils"
brew "awscli"
brew "bash"
brew "bat"
brew "node"
brew "bitwarden-cli"
brew "glib"
brew "python@3.9"
brew "colordiff"
brew "coreutils"
brew "dive"
brew "exa"
brew "fd"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libass"
brew "pango"
brew "ffmpeg"
brew "findutils"
brew "gawk"
brew "gdk-pixbuf"
brew "git"
brew "git-crypt"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "gobject-introspection"
brew "openjdk@17"
brew "gradle"
brew "librsvg"
brew "graphviz"
brew "helm"
brew "hexyl"
brew "htop"
brew "httpie"
brew "openssl@3"
brew "iperf3"
brew "iproute2mac"
brew "istioctl"
brew "jenv"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "kubectx"
brew "lazydocker"
brew "mas"
brew "openjdk"
brew "maven"
brew "minikube"
brew "neovim"
brew "nyancat"
brew "octant"
brew "openapi-generator"
brew "pinentry-mac"
brew "procs"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rbenv"
brew "rig"
brew "sbt"
brew "speedtest-cli"
brew "tcpdump"
brew "telnet"
brew "terraform"
brew "tig"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "yq"
brew "zsh"
brew "zsh-completions"
brew "argoproj/tap/kubectl-argo-rollouts"
brew "hudochenkov/sshpass/sshpass"
brew "weaveworks/tap/eksctl"
cask "appcleaner"
cask "charles"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "hammerspoon"
cask "iina"
cask "iterm2"
cask "karabiner-elements"
cask "keycastr"
cask "lens"
cask "ngrok"
cask "parallels"
cask "postman"
cask "slack"
cask "sourcetree"
cask "tabby"
cask "tableplus"
cask "temurin17"
cask "visual-studio-code"
cask "wireshark"
mas "AutoTyper", id: 1381314885
mas "Brother iPrint&Scan", id: 1193539993
mas "Dino VPN", id: 1631721148
mas "Fantastical", id: 975937182
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iShot", id: 1485844094
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PhotoScape X", id: 929507092
mas "RunCat", id: 1429033973
mas "ScreenBrush", id: 1233965871
mas "Telegram Lite", id: 946399090
mas "The Unarchiver", id: 425424353
mas "카카오톡", id: 869223134
mas "한컴오피스 한글 2014 VP 뷰어", id: 416746898
