tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "asciinema"
brew "python@3.9"
brew "awscli"
brew "bash"
brew "bat"
brew "node"
brew "bitwarden-cli"
brew "glib"
brew "colordiff"
brew "coreutils"
brew "dive"
brew "exa"
brew "fd"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "ffmpeg"
brew "findutils"
brew "gawk"
brew "gdk-pixbuf"
brew "git"
brew "git-crypt"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "openjdk"
brew "gradle"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "hexyl"
brew "htop"
brew "httpie"
brew "iproute2mac"
brew "jenv"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "mas"
brew "maven"
brew "minikube"
brew "neovim"
brew "nyancat"
brew "octant"
brew "openapi-generator"
brew "openssl@3"
brew "pinentry-mac"
brew "procs"
brew "pyenv"
brew "rbenv"
brew "sbt"
brew "speedtest-cli"
brew "tcpdump"
brew "telnet"
brew "tig"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
cask "appcleaner"
cask "charles"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "hammerspoon"
cask "iina"
cask "iterm2"
cask "karabiner-elements"
cask "lens"
cask "ngrok"
cask "parallels"
cask "postman"
cask "slack"
cask "sourcetree"
cask "tableplus"
cask "visual-studio-code"
cask "wireshark"
cask "zulu17"
mas "Brother iPrint&Scan", id: 1193539993
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iShot", id: 1485844094
mas "Keynote", id: 409183694
mas "Memo", id: 1212409035
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "ScreenBrush", id: 1233965871
mas "Telegram Lite", id: 946399090
mas "The Unarchiver", id: 425424353
mas "카카오톡", id: 869223134
mas "한컴오피스 한글 2014 VP 뷰어", id: 416746898
